discord:
  token: xxxxx
  debug_log: true

redis:
  url: redis://127.0.0.1:6379/0

mysql:
  url: 'mysql://user:pass@127.0.0.1:3306/duck_test'

web_auth:
  username: username
  password: password

giphy:
  key: xxxxx

wolfram_alpha:
  appid: xxxxx

twilio:
  outgoing_phone_number: "+15554443333"
  account_sid: ACxxxx
  auth_token: xxxxx

openai:
  access_token: xxxxx

aws:
  access_key_id: xxx
  secret_access_key: xxx

duck:
  api_key: xxxxxxxxxxxxxxxxxx

servers: {}
